# The name of the workflow on the "Actions" tab
name: Build launcher

# Run build on every push or pull request but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    # Name of the workflow itself
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Installing dependencies
        run: npm install
      - name: Compiling TypeScript files
        run: |
          sh tools/make_ts_compile.sh
      - name: Compiling Sass files
        run: |
          sh tools/make_sass_compile.sh
      - name: Building launcher (Windows -- x64 and x86)
        run: |
          sh tools/make_app_windows.sh
      - name: Building launcher (Linux -- AppImage, deb and tar.gz)
        run: |
          sh tools/make_app_linux.sh